# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on vehicle run tag @s add deadism.weapon.cooldown
execute on vehicle run tag @s add deadism.weapon.reloading