# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers run data modify entity @s interpolation_duration set value 0
execute on vehicle run tag @s add deadism.weapon.cooldown