# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.equip.frame
scoreboard objectives remove aj.unequip.frame
scoreboard objectives remove aj.equip2.frame
scoreboard objectives remove aj.walk.frame
scoreboard objectives remove aj.idle_still.frame
scoreboard objectives remove aj.equip_empty.frame
scoreboard objectives remove aj.shoot.frame
scoreboard objectives remove aj.shoot2.frame
scoreboard objectives remove aj.shoot3.frame
scoreboard objectives remove aj.shoot4.frame
scoreboard objectives remove aj.shoot5.frame
scoreboard objectives remove aj.shoot_final.frame
scoreboard objectives remove aj.reload_mid.frame
scoreboard objectives remove aj.reload_empty.frame
scoreboard objectives remove aj.sprint.frame
scoreboard objectives remove aj.use.frame
scoreboard objectives remove aj.idle2.frame
scoreboard objectives remove aj.idle.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:glock)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'glock'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']