# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0 ^-0.1875 ^-0.25 ~0 ~0
data modify entity @s data.cameras.camera2 merge value { px: 0, py: -0.1875, pz: -0.25, ry: 0, rx: 0 }