# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^-0.20625 ^-1.1 ^0.275 ~0 ~90
data modify entity @s data.locators.barrel1 merge value { px: -0.20625, py: -1.1, pz: 0.275, ry: 0, rx: 90 }