# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gun_glock18.node.loader] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_loader set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gun_glock18.node.mag] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_mag set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gun_glock18.node.light] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_light set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gun_glock18.node.gun] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_gun set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gun_glock18.node.right_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_arm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gun_glock18.node.left_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_arm set from storage animated_java:gu out