# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s transformation.scale set value [0.0f, 0.0f, 0.0f]
function animated_java:global/util/get_entity_stack_uuids