# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on vehicle run tag @s remove deadism.IsSprinting
execute on vehicle run tag @s remove deadism.IsWalking
execute on vehicle run tag @s remove deadism.weapon.cooldown
function animated_java:glock/animations/idle_still/tween {to_frame: 0, duration: 1}