# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$function animated_java:gun_glock18/animations/cs_glock18_draw/zzz/apply_frame {frame: $(frame)}
execute on passengers run data modify entity @s[tag=!aj.global.data] start_interpolation set value -1
return 1