# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.gun_glock18.root] run return 0
execute if entity @s[tag=aj.gun_glock18.animation.cs_glock18_idle.playing] run function animated_java:gun_glock18/animations/cs_glock18_idle/zzz/on_tick
execute if entity @s[tag=aj.gun_glock18.animation.cs_glock18_reload.playing] run function animated_java:gun_glock18/animations/cs_glock18_reload/zzz/on_tick
execute if entity @s[tag=aj.gun_glock18.animation.cs_glock18_shoot.playing] run function animated_java:gun_glock18/animations/cs_glock18_shoot/zzz/on_tick
execute if entity @s[tag=aj.gun_glock18.animation.cs_glock18_shoot_empty.playing] run function animated_java:gun_glock18/animations/cs_glock18_shoot_empty/zzz/on_tick
execute if entity @s[tag=aj.gun_glock18.animation.cs_glock18_draw.playing] run function animated_java:gun_glock18/animations/cs_glock18_draw/zzz/on_tick
execute on passengers run rotate @s ~ ~