# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:glock/animations/idle_still/zzz/apply_frame {frame: 523}
scoreboard players add @s aj.idle_still.frame 1