# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
execute as @p run function deadism:zprivate/weapons/pistols/glock/reload_end
data modify entity @s text set value [{"score":{name:"@p", "objective":"deadism.weapon.AMMO.IN_GUN"}, "font":"deadism:f25bankprinter"}, "/", {"score":{"name":"@p", objective:"deadism.weapon.AMMO.RELOADABLE_AMOUNT"}}]
data modify entity @s view_range set value 1f