# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
playsound deadism:sfx.weapons.glock.shoot master @a ~ ~ ~ 1 1
function deadism:zprivate/weapons/shoot_particle
data modify entity @s view_range set value 0f
item replace entity @s contents with minecraft:sea_lantern