# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.cs_glock18_idle.frame
scoreboard objectives remove aj.cs_glock18_reload.frame
scoreboard objectives remove aj.cs_glock18_shoot.frame
scoreboard objectives remove aj.cs_glock18_shoot_empty.frame
scoreboard objectives remove aj.cs_glock18_draw.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:gun_glock18)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'gun_glock18'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']