# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.glock.root] run return run tellraw @a [{color:'red',text:''},{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:glock)'},'\n → ᴇʀʀᴏʀ: ',{color:'red',underlined:true,text:'Function Not Executed as Root Entity'},'\n\n ',{color:'yellow',text:'[This Function]',hover_event:{action:show_text,value:[{color:'yellow',text:'animated_java:glock/animations/equip_empty/play'}]}}," must be executed as the rig's root entity.",{color:'white',text:'\n\n ≡ '},{color:'aqua',underlined:true,text:'ꜱʜᴏᴡ ᴇxᴀᴍᴘʟᴇ ᴄᴏᴍᴍᴀɴᴅ',click_event:{action:suggest_command,command:'/execute as @e[tag=aj.glock.root] run function animated_java:glock/animations/equip_empty/play'}},'\n\n ',{color:'blue',italic:true,underlined:true,text:'▶ Learn More ◀',click_event:{action:open_url,url:'https://animated-java.dev/docs/rigs/controlling-a-rig-instance'}},'\n']
function animated_java:glock/animations/pause_all
tag @s add aj.glock.animation.equip_empty.playing
scoreboard players set @s aj.equip_empty.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:glock/animations/equip_empty/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only