# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:glock/animations/sprint/zzz/apply_frame {frame: 24}
scoreboard players add @s aj.sprint.frame 1