# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add deadism.weapon.glock
tag @s add deadism.weapon
tag @s add deadism.weapon.NEW
execute on passengers run data modify entity @s view_range set value 0.05f