# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.gun_glock18.node.loader] run data modify entity @s {} merge from storage animated_java:gun_glock18/animations cs_glock18_shoot.$(frame).b_loader
$execute on passengers if entity @s[tag=aj.gun_glock18.node.mag] run data modify entity @s {} merge from storage animated_java:gun_glock18/animations cs_glock18_shoot.$(frame).b_mag
$execute on passengers if entity @s[tag=aj.gun_glock18.node.light] run data modify entity @s {} merge from storage animated_java:gun_glock18/animations cs_glock18_shoot.$(frame).b_light
$execute on passengers if entity @s[tag=aj.gun_glock18.node.gun] run data modify entity @s {} merge from storage animated_java:gun_glock18/animations cs_glock18_shoot.$(frame).b_gun
$execute on passengers if entity @s[tag=aj.gun_glock18.node.right_arm] run data modify entity @s {} merge from storage animated_java:gun_glock18/animations cs_glock18_shoot.$(frame).b_right_arm
$execute on passengers if entity @s[tag=aj.gun_glock18.node.left_arm] run data modify entity @s {} merge from storage animated_java:gun_glock18/animations cs_glock18_shoot.$(frame).b_left_arm
return 1