# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args.export_namespace set from entity @s data.export_namespace
data modify entity @s data.rig_hash set value '8bd46621525e416b648f781059eca6491629f47533cd4eb6737da6dca206aa14'